USE [master]
GO

/****** Object:  Database [EventPlatformDb]    Script Date: 12/03/2026 6:53:54 ******/
CREATE DATABASE [EventPlatformDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EventPlatformDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS01\MSSQL\DATA\EventPlatformDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EventPlatformDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS01\MSSQL\DATA\EventPlatformDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EventPlatformDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EventPlatformDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EventPlatformDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EventPlatformDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EventPlatformDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EventPlatformDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [EventPlatformDb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [EventPlatformDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EventPlatformDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EventPlatformDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EventPlatformDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EventPlatformDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EventPlatformDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EventPlatformDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EventPlatformDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EventPlatformDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [EventPlatformDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EventPlatformDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EventPlatformDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EventPlatformDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EventPlatformDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EventPlatformDb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [EventPlatformDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EventPlatformDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EventPlatformDb] SET  MULTI_USER 
GO

ALTER DATABASE [EventPlatformDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EventPlatformDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EventPlatformDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EventPlatformDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EventPlatformDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EventPlatformDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EventPlatformDb] SET QUERY_STORE = ON
GO

ALTER DATABASE [EventPlatformDb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [EventPlatformDb] SET  READ_WRITE 
GO


